// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH8-HDQm09tHm8O9lunPB2FFUUFksyaMc',
    appId: '1:979447508831:web:bc915998689855a93190ea',
    messagingSenderId: '979447508831',
    projectId: 'todo-2f86b',
    authDomain: 'todo-2f86b.firebaseapp.com',
    storageBucket: 'todo-2f86b.firebasestorage.app',
    measurementId: 'G-4Y95LQMLY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:804059036502:android:app123456789',
    messagingSenderId: '804059036502',
    projectId: 'your-todo-project',
    storageBucket: 'your-todo-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTOE65VxwizE28wC5ZB7oMtsGZw5Z6orc',
    appId: '1:979447508831:ios:42221416f24a974f3190ea',
    messagingSenderId: '979447508831',
    projectId: 'todo-2f86b',
    storageBucket: 'todo-2f86b.firebasestorage.app',
    iosClientId: '979447508831-b1tidqhrkpsbcd382t4q48c6hk4f61n1.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTOE65VxwizE28wC5ZB7oMtsGZw5Z6orc',
    appId: '1:979447508831:ios:42221416f24a974f3190ea',
    messagingSenderId: '979447508831',
    projectId: 'todo-2f86b',
    storageBucket: 'todo-2f86b.firebasestorage.app',
    iosClientId: '979447508831-b1tidqhrkpsbcd382t4q48c6hk4f61n1.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH8-HDQm09tHm8O9lunPB2FFUUFksyaMc',
    appId: '1:979447508831:web:0f567a80c596d1fe3190ea',
    messagingSenderId: '979447508831',
    projectId: 'todo-2f86b',
    authDomain: 'todo-2f86b.firebaseapp.com',
    storageBucket: 'todo-2f86b.firebasestorage.app',
    measurementId: 'G-B4QCFHLFNC',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyA2ov6sGjAG_Ul2UJTF_FLHtxoHt8TYlok',
    appId: '1:979447508831:android:4200e047693077d73190ea',
    messagingSenderId: '979447508831',
    projectId: 'todo-2f86b',
    storageBucket: 'todo-2f86b.firebasestorage.app',
  );

}